version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=SuperSecret
      - MYSQL_DATABASE=otrs
      - MYSQL_USER=otrs
      - MYSQL_PASSWORD=otrs
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/config/utf8.cnf:/etc/mysql/conf.d/utf8.cnf'
      - './db/config/otrs.cnf:/etc/mysql/conf.d/otrs.cnf'
      - '/etc/localtime:/etc/localtime:ro'
    restart: always
  otrs:
    image: croc/otrs 
    environment:
      - OTRS_DB=otrs
      - OTRS_DB_HOST=db
      - OTRS_DB_USER=otrs
      - OTRS_DB_PASSWORD=otrs
#      - OTRS_LANGUAGE=hu
#      - OTRS_TICKET_COUNTER=1000
#      - OTRS_NUMBER_GENERATOR=DateChecksum
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - db 
    ports:
      - '80:80'
    restart: always
